FROM ubuntu:22.04

# 国内镜像源和系统更新/安装
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    # 安装 Node.js
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get update && \
    # 避免安装过程中的交互操作
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    python3 \
    python3-pip \
    build-essential \
    debhelper \
    g++ \
    gcc-11 \
    g++-11 \
    p7zip-full \
    pkg-config \
    cmake \
    ninja-build \
    autoconf \
    automake \
    libtool \
    curl \
    sudo \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libfontconfig-dev \
    libx11-dev \
    libxext-dev \
    libxfixes-dev \
    libxi-dev \
    libxrender-dev \
    libxcb1-dev \
    libx11-xcb-dev \
    libxcb-glx0-dev \
    libsqlite3-dev \
    libcairo2-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    mesa-common-dev \
    libgstreamer1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libhunspell-dev \
    libxcb-xfixes0-dev \
    ttf-mscorefonts-installer \
    fonts-dejavu \
    fonts-liberation \
    openjdk-11-jdk \
    nodejs \
    npm && \
    # 清理 apt 缓存
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # 配置 python 和 shell
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm /bin/sh && \
    ln -s /bin/bash /bin/sh && \
    # 配置 npm 源
    npm config set registry https://npmreg.proxy.ustclug.org && \
    # 安装 grunt-cli 和 pkg
    npm install -g grunt-cli pkg

# 设置环境变量
ENV TZ=Asia/Shanghai \
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 \
PATH=$PATH:/usr/lib/jvm/java-11-openjdk-amd64/bin \
DEBIAN_FRONTEND=noninteractive \
BUILD_MODULES=""

# 设置时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 设置工作目录
WORKDIR /onlyoffice/build_tools

# 使用 ENTRYPOINT 设置默认命令
ENTRYPOINT ["/bin/bash"]

# 设置默认参数
CMD ["-c", "cd tools/linux && python ./automate.py ${BUILD_MODULES}"]